spring.application.name=personaumg4
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/programacion_3
spring.datasource.username=postgres
spring.datasource.password=hilda

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.graphql.cors.allowed-origins=*
spring.graphql.cors.allowed-headers=*
spring.graphql.cors.allowed-methods=*